spring.application.name=leadcommand

server.port=8081

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

db.server.ip=localhost
db.server.port=5432

# Configuração do Master Database (PostgreSQL)
multitenancy.mtapp.master.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/sell_motors_leads
multitenancy.mtapp.master.datasource.username=${DB_USERNAME:sellmotors}
multitenancy.mtapp.master.datasource.password=${DB_PASSWORD:sellmotors}
multitenancy.mtapp.master.datasource.driverClassName=org.postgresql.Driver

# Configurações do Pool (HikariCP)
multitenancy.mtapp.master.datasource.connectionTimeout=20000
multitenancy.mtapp.master.datasource.maxPoolSize=20
multitenancy.mtapp.master.datasource.minIdle=5
multitenancy.mtapp.master.datasource.idleTimeout=300000
multitenancy.mtapp.master.datasource.poolName=masterdb-pool-sell_motors_leads

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_HTTP:http}://${JWT_URL:localhost:8080}/oauth2/jwks

#RABBIT MQ CONFIGURATION****************
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=sellmotors
spring.rabbitmq.password=sellmotors