spring.application.name=gateway
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8081/eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.threads.virtual.enabled=true

spring.cloud.discovery.enabled=true
eureka.instance.prefer-ip-address=true
eureka.instance.preferIpAddress=true
eureka.instance.instance-id=${spring.application.name}:${random.int}