CREATE TABLE vehicles (
                          id UUID PRIMARY KEY,
                          title VARCHAR(255) NOT NULL,
                          description TEXT,
                          video_id VARCHAR(255),
                          category_id VARCHAR(50),
                          price NUMERIC(19, 2),
                          currency_id VARCHAR(10),
                          listing_type_id VARCHAR(50),
                          available_quantity INTEGER,
                          status_veiculo VARCHAR(50),
                          attributes JSONB,
                          channels JSONB,
                          locations JSONB,
                          pictures JSONB,
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NOT NULL,
                          deleted_at TIMESTAMP,
                          entity_status VARCHAR(50) NOT NULL DEFAULT 'ATIVO',
                          created_by UUID NOT NULL
);