spring.application.name=leadread

# MongoDB Config

spring.mongodb.database=sell-motors-query
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.username='sell-motors-query'
spring.mongodb.password='sell-motors-query'
spring.mongodb.representation.uuid=standard

# Configuração EUREKA
eureka.client.service-url.defaultZone=http://localhost:8081/eureka
eureka.instance.instance-id=${spring.application.name}:${random.int}
server.port=0