spring.application.name=authcommand
db.server.ip=localhost
db.server.port=5432

jwt.public.key=classpath:public.pem
jwt.private.key=classpath:private.pem

spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

tenant.db.port=${DB_PORT:5432}
tenant.db.username=${DB_USERNAME:sellmotors}
tenant.db.password=${DB_PASSWORD:sellmotors}

# Configuração do Master Database (PostgreSQL)
multitenancy.mtapp.master.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/sell_motors_master
multitenancy.mtapp.master.datasource.username=${DB_USERNAME:sellmotors}
multitenancy.mtapp.master.datasource.password=${DB_PASSWORD:sellmotors}
multitenancy.mtapp.master.datasource.driverClassName=org.postgresql.Driver

# Configurações do Pool (HikariCP)
multitenancy.mtapp.master.datasource.connectionTimeout=20000
multitenancy.mtapp.master.datasource.maxPoolSize=20
multitenancy.mtapp.master.datasource.minIdle=5
multitenancy.mtapp.master.datasource.idleTimeout=300000
multitenancy.mtapp.master.datasource.poolName=masterdb-pool-sellmotors_master