spring.application.name=sync

#RABBIT MQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=sellmotors
spring.rabbitmq.password=sellmotors

# MongoDB Config

spring.mongodb.database=sell-motors-query
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.username=sync
spring.mongodb.password=sync
spring.mongodb.representation.uuid=standard
spring.data.mongodb.auto-index-creation=true


# Configuração EUREKA
eureka.client.service-url.defaultZone=http://localhost:8081/eureka
eureka.instance.instance-id=${spring.application.name}:${random.int}
server.port=0