spring.application.name=sync
server.port=8084

#RABBIT MQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=sellmotors
spring.rabbitmq.password=sellmotors

# MongoDB Config

spring.data.mongodb.database=sell-motors-query
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=sellmotors
spring.data.mongodb.password=sellmotors