CREATE TABLE IF NOT EXISTS unit_measures (
    id BINARY(16) PRIMARY KEY,
    acronym VARCHAR(6) NOT NULL UNIQUE,
    description VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL,
    created_by BINARY(16) NOT NULL ,
    entity_status VARCHAR(20) NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS tax_rules (
    id BINARY(16) PRIMARY KEY,
    service_code VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    cnae_id BIGINT NOT NULL,
    municipal_code VARCHAR(7) NOT NULL,
    municipal_activity_code VARCHAR(50) NOT NULL,
    national_tax_code VARCHAR(50) NOT NULL,
    nbs VARCHAR(50) NOT NULL,
    pis DOUBLE,
    ir DOUBLE,
    confins DOUBLE,
    inss DOUBLE,
    csll DOUBLE,
    ibpt DOUBLE,
    initial_effective_date DATE,
    final_effective_date DATE,
    is_default BOOLEAN DEFAULT FALSE,
    tax_nature VARCHAR(100) NOT NULL,
    enforceability VARCHAR(100) NOT NULL,
    process_number VARCHAR(100),
    tax_type VARCHAR(50) NOT NULL,
    iss DOUBLE NOT NULL,
    allows_retention BOOLEAN DEFAULT FALSE,
    allows_deduction BOOLEAN DEFAULT FALSE,
    created_by BINARY(16) NOT NULL ,
    created_at DATETIME NOT NULL,
    entity_status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_tax_rule_cnae FOREIGN KEY (cnae_id) REFERENCES financial_master.cnaes(id)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS clients (
    id BINARY(16) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    inscription VARCHAR(14) NOT NULL,
    inscription_type VARCHAR(20) NOT NULL,
    inscription_date DATE NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    telephone VARCHAR(20) NOT NULL,
    cell_phone VARCHAR(20),
    accounting_account VARCHAR(50),
    state_registration VARCHAR(50),
    state_registration_date DATE,
    municipal_registration VARCHAR(50),
    created_by BINARY(16) NOT NULL ,
    created_at DATETIME NOT NULL,
    creation_status VARCHAR(20) NOT NULL,
    entity_status VARCHAR(20) NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS suppliers (
    id BINARY(16) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    inscription VARCHAR(14) NOT NULL,
    inscription_type VARCHAR(20) NOT NULL,
    inscription_date DATE NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    telephone VARCHAR(20) NOT NULL,
    cell_phone VARCHAR(20),
    accounting_account VARCHAR(50),
    state_registration VARCHAR(50),
    state_registration_date DATE,
    municipal_registration VARCHAR(50),
    created_by BINARY(16) NOT NULL ,
    created_at DATETIME NOT NULL,
    creation_status VARCHAR(20) NOT NULL,
    entity_status VARCHAR(20) NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS services_products (
    id BINARY(16) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    code VARCHAR(60) NOT NULL UNIQUE,
    price DECIMAL(19, 2) NOT NULL,
    cost DECIMAL(19, 2),
    unit_measure_id BINARY(16),
    tax_rule_id BINARY(16) NOT NULL,
    supplier_id BINARY(16),
    description TEXT,
    created_by BINARY(16) NOT NULL ,
    created_at DATETIME NOT NULL,
    entity_status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_sp_unit FOREIGN KEY (unit_measure_id) REFERENCES unit_measures(id),
    CONSTRAINT fk_sp_tax FOREIGN KEY (tax_rule_id) REFERENCES tax_rules(id),
    CONSTRAINT fk_sp_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS addresses (
    id BINARY(16) PRIMARY KEY,
    zip_code VARCHAR(8) NOT NULL,
    street_address VARCHAR(255) NOT NULL,
    number INT NOT NULL,
    neighborhood_type VARCHAR(50) NOT NULL,
    neighborhood VARCHAR(100) NOT NULL,
    complement VARCHAR(100),
    state CHAR(2) NOT NULL,
    city VARCHAR(100) NOT NULL,
    city_ibge VARCHAR(50) NOT NULL,
    created_for VARCHAR(30) NOT NULL,
    address_of_id BINARY(16) NOT NULL,
    created_by BINARY(16) NOT NULL ,
    created_at DATETIME NOT NULL,
    entity_status VARCHAR(20) NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS contacts (
    id BINARY(16) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    telephone VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL,
    position VARCHAR(100) NOT NULL,
    send_invoice_payment_slip BOOLEAN DEFAULT FALSE,
    created_for VARCHAR(20) NOT NULL,
    contact_of_id BINARY(16) NOT NULL,
    created_by BINARY(16) NOT NULL ,
    created_at DATETIME NOT NULL,
    entity_status VARCHAR(20) NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS bank_accounts (
    id BINARY(16) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    account_type VARCHAR(255),
    bank_account_entity_type VARCHAR(50),
    bank VARCHAR(50),
    branch_number VARCHAR(20),
    branch_digit VARCHAR(5),
    account_number VARCHAR(20),
    account_digit VARCHAR(5),
    pix_key_type VARCHAR(50),
    pix_key VARCHAR(255),
    generate_qr_code BOOLEAN,
    initial_balance DECIMAL(19, 2),
    initial_balance_date DATE,
    issues_slips BOOLEAN,
    created_at DATETIME NOT NULL,
    created_by BINARY(16) NOT NULL,
    entity_status VARCHAR(20) NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS services_contracts (
    id BINARY(16) PRIMARY KEY,
    client_id BINARY(16),
    client_name VARCHAR(255),
    contract_type VARCHAR(50),
    contract_status VARCHAR(50),
    start_date DATE,
    adjustment VARCHAR(50),
    notify_adjustment INT,
    adjustment_index DECIMAL(19, 4),
    month_adjustment DATE,
    signed_contract BOOLEAN,
    signed_by VARCHAR(255),
    invoice_automatically BOOLEAN,
    send_nfse BOOLEAN,
    entity_status VARCHAR(20) NOT NULL,
    bill_extra_month VARCHAR(50),
    billing_model VARCHAR(50),
    payment_method VARCHAR(50),
    bank_account_id BINARY(16),
    bank_account_name VARCHAR(255),
    has_custom_partnership_discount BOOLEAN,
    total_contract_gross_amount DECIMAL(19, 2),
    total_services_invoicing_amount DECIMAL(19,2),
    total_services_invoicing_discount_amount DECIMAL(19, 2),
    total_services_cancelled_amount DECIMAL(19, 2),
    total_services_free_amount DECIMAL(19, 2),
    total_contract_net_amount DECIMAL(19, 2),
    retain_aliquot_pis BOOLEAN,
    retain_aliquot_ir BOOLEAN,
    retain_aliquot_confins BOOLEAN,
    retain_aliquot_inss BOOLEAN,
    retain_aliquot_csll BOOLEAN,
    attachment_link TEXT,
    attachment_name TEXT,
    observation TEXT,
    last_invoicing_at DATETIME,
    is_invoicing BOOLEAN,
    created_at DATETIME NOT NULL,
    created_by BINARY(16) NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS service_contract_items (
    id BINARY(16) PRIMARY KEY,
    service_contract_id BINARY(16) NOT NULL,
    service_product_id BINARY(16),
    unit_price DECIMAL(19, 2),
    quantity INT,
    discount DECIMAL(19, 2),
    total DECIMAL(19, 2),
    apply_discount BOOLEAN,
    obsevations TEXT,
    item_status VARCHAR(50),
    entity_status VARCHAR(20),
    created_at DATETIME,
    created_by BINARY(16) NOT NULL,
    CONSTRAINT fk_sci_contract FOREIGN KEY (service_contract_id) REFERENCES services_contracts(id)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sales (
    id BINARY(16) PRIMARY KEY,
    client_id BINARY(16),
    client_name VARCHAR(255),
    sale_date DATE,
    competence DATE,
    send_nfse BOOLEAN,
    total_sale_gross_amount DECIMAL(19, 2),
    total_services_invoicing_amount DECIMAL(19, 2),
    total_services_invoicing_discount_amount DECIMAL(19, 2),
    total_services_cancelled_amount DECIMAL(19, 2),
    total_services_free_amount DECIMAL(19, 2),
    total_sale_net_amount DECIMAL(19, 2),
    with_tax_withheld BOOLEAN,
    bank_account_id BINARY(16),
    bank_account_name VARCHAR(255),
    receipt_type VARCHAR(50),
    installment_count INT,
    has_down_payment BOOLEAN,
    attachments TEXT,
    observation TEXT,
    sale_status VARCHAR(50),
    entity_status VARCHAR(20),
    created_at DATETIME,
    created_by BINARY(16) NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sale_items (
    id BINARY(16) PRIMARY KEY,
    sale_id BINARY(16),
    service_product_id BINARY(16),
    unit_price DECIMAL(19, 2),
    quantity INT,
    discount DECIMAL(19, 2),
    total DECIMAL(19, 2),
    apply_discount BOOLEAN,
    obsevations TEXT,
    item_status VARCHAR(50),
    entity_status VARCHAR(20),
    created_at DATETIME,
    created_by BINARY(16) NOT NULL,
    CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) REFERENCES sales(id)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS installments (
    id BINARY(16) PRIMARY KEY,
    sale_id BINARY(16),
    due_date DATE,
    installment_amount DECIMAL(19, 2),
    observation TEXT,
    created_at DATETIME,
    entity_status VARCHAR(20),
    created_by BINARY(16) NOT NULL,
    CONSTRAINT fk_installments_sale FOREIGN KEY (sale_id) REFERENCES sales(id)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS payments (
    id BINARY(16) PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    category_id BINARY(16) NOT NULL,
    category_name VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    bank_account_id BINARY(16) NOT NULL,
    bank_account_name VARCHAR(255),
    amount DECIMAL(19, 2) NOT NULL,
    due_date DATE NOT NULL,
    is_paid BOOLEAN NOT NULL,
    payment_date DATE NOT NULL,
    discounts_fees DECIMAL(19, 2) DEFAULT 0.00,
    penalty_interest DECIMAL(19, 2) DEFAULT 0.00,
    total_paid DECIMAL(19, 2) DEFAULT 0.00,
    payment_type VARCHAR(50) NOT NULL,
    competence_date DATE NOT NULL,
    cost_center VARCHAR(100),
    document_number VARCHAR(50),
    observation TEXT,
    supplier_id BINARY(16),
    supplier_name VARCHAR(255),
    created_at DATETIME NOT NULL,
    created_by BINARY(16) NOT NULL,
    entity_status VARCHAR(20) NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS receipts (
    id BINARY(16) PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    category_id BINARY(16) NOT NULL,
    category_name VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    bank_account_id BINARY(16) NOT NULL,
    bank_account_name VARCHAR(255),
    amount DECIMAL(19, 2) NOT NULL,
    due_date DATE NOT NULL,
    is_paid BOOLEAN NOT NULL,
    payment_date DATE,
    discounts_fees DECIMAL(19, 2) DEFAULT 0.00,
    penalty_interest DECIMAL(19, 2) DEFAULT 0.00,
    total_received DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    payment_type VARCHAR(50) NOT NULL,
    client_id BINARY(16),
    client_name VARCHAR(255),
    accrual_date DATE NOT NULL,
    cost_center VARCHAR(100),
    document_number VARCHAR(50),
    observation TEXT,
    created_at DATETIME NOT NULL,
    created_by BINARY(16) NOT NULL,
    entity_status VARCHAR(20) NOT NULL
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS categories (
    id BINARY(16) PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_by BINARY(16) NOT NULL,
    created_at DATETIME NOT NULL,
    entity_status VARCHAR(20) NOT NULL,
    INDEX idx_categories_name (name)
    ) ENGINE=InnoDB;